# Heavy metals {#hm}

Qui il pdf del progetto: [**Mechanisms of gene regulation during the ericoid endomycorrhizal interaction**](Documents/CHIAPELLO_proposal.pdf)

## 20211217 {#D20211217}

### Preparazione degli inoculi liquidi. 

Sono state preparate 30 beute: 


- 15 per _O. maius_ A:
  - 5 Controlli 
  - 5 trattati con 0.0.05mM Cd
  - 5 trattati con 0.05mM Cd

- 15 per _O. maius_ Zn:
  - 5 Controlli 
  - 5 trattati con 0.0.05mM Cd
  - 5 trattati con 0.05mM Cd

Terreno di controllo: [Czapec-Glucosio](Documents/media1.pdf) a cui è stato aggiunto CdSO~4~ alla concentrazione necessaria. Il CdSO~4~ è stato sterilizzato per filtrazione (filtri da 0.2)

Sono state utilizzate beute da 250 ml nelle quali aggiungere 100 ml di terreno di coltura


## 20220117 {#D20220117}

Inoculi controllati (dell'esperimento \@ref(D20211217))dopo un mese di crescita. I controlli sono tutti normali, mentre il ceppo suscettibile (_O. maius_ A) non è cresciuto su nessuna concentrazione di Cd, mentre il ceppo resistente (_O. maius_ Zn) non è cresciuto sulla concentrazione più elevata di Cd e sulla meno elevata è cresciuto molto poco.

**Le concentrazioni devono essere riviste**. Probabilmente questo terreno non va bene con concentrazioni così alte. Tutte le prove a 0.025 e 0.05 erano state fatte su Czapek-pectina, un terreno più ricco, che probabilmente aiutava meglio il fungo a rispondere ai metalli.

Procederemo comunque alla filtrazione dei miceli che potremo poi usare come prove per le estrazioni di RNA.

Di tutte le beute una sola era contaminata!

Molte delle piastre lasciate in camera di crescita erano invece contaminate da acari (lasciano dei percorsi sulle piastre). Erano contaminate anche delle piastre chiuse. 

## 20220121 {#D20220121}

Pulizia laboratorio.

Contattare Chiara per la prossima settimana.

## 20220124 {#D20220124}

### Preparazione dei materiali e organizzazione per domani

Domani (\@ref(D20220125)) Chiara e Miriana verranno per iniziare a preparare i materiali per filtrare le beute di _O. maius_ A e Zn cresciute su Cd nell'ultimo mese e preparare le piastre di Czapek-dox


## 20220125 {#D20220125}

### Sterilizzare tutti i materiali necessari per filtrare le beute
  - buckner    
  - filtri di carta    
  - pinzette    
  - provette da 1,5 o 2 ml    
  - 1L di H~2~O    

### Preparare delle nuove piastre utilizzando il Czapeck-dox     

### Verificare che il sistema a muro per fare il vuoto per filtrare funzioni senza problemi

## 20220126 {#D20220126}

### Filtrare le colture

- Fare foto delle beute

- Peso dei miceli filtrati

```{r tabella-pesi-20220126}
library(tidyverse)
library(kableExtra)

tb <- tibble(Sample = NA,
       Cd = NA,
       Weight_g = NA)

tb %>%
  kbl(caption = str_glue("Weight in gram of _O. maius_ Cd and A grown on different concentrations of Cd")) %>%
  kable_paper() %>%
  kable_styling(bootstrap_options = c("striped", "condensed"),
                full_width = TRUE, html_font = "Cambria",
                fixed_thead = TRUE, position = "center")

```

### Lavare le beute

## 20220127 {#D20220127}

## 20220128 {#D20220128}
