--- 
title: "Labbook"
author: "Marco Chiapello"
date: "Last update: `r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: mchiapello/2022-UNITO-Labbook
---

# Preface

## Prova 1
```{r table1}
library(kableExtra)
dt <- mtcars[1:5, 1:6]

dt %>%
      kbl(caption = "Recreating booktabs style table") %>%
        kable_styling()
```

## PRova2

```{r table2}
dt %>%
  kbl(caption = "Recreating booktabs style table") %>%
  kable_paper() %>%
  kable_styling(bootstrap_options = c("striped", "condensed"),
                full_width = F, html_font = "Cambria",
                fixed_thead = T) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(4, background = "yellow")
```

## PRova3
```{r table3}
dt %>%
  kbl(caption = "Recreating booktabs style table") %>%
  kable_minimal()
```

La piu bella e \@ref(tab:table2).


```{r test}
source("protocols/_main.R")

reac <- 10
pcr %>%
  mutate(VolumeFinal = VolumeInit * reac) %>%
  add_row(Reagents = "Total", InitialConcetration = NA,
          VolumeInit = sum(pcr$VolumeInit), VolumeFinal = sum(pcr$VolumeFinal)) %>%
  kbl(caption = str_glue("PCR mix for {reac} samples")) %>%
  kable_paper() %>%
  kable_styling(bootstrap_options = c("striped", "condensed"),
                full_width = F, html_font = "Cambria",
                fixed_thead = T) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(4, background = "yellow") %>%
  pack_rows("Not add to the mix", 6, 6)
```


